apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"run":"vault"},"name":"vault","namespace":"default"},"spec":{"ports":[{"port":8200,"protocol":"TCP","targetPort":8200}],"selector":{"run":"vault"},"type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2023-11-09T14:19:50Z"
  labels:
    run: vault
  name: vault
  namespace: default
  resourceVersion: "5511"
  uid: ca0f1747-a2b7-4162-a046-50ade75c5b62
spec:
  clusterIP: 10.98.13.66
  clusterIPs:
  - 10.98.13.66
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30687
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    run: vault
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
