apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: artshirshov
spec:
  cidr: 192.168.0.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: company == "artshirshov"
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: sleepy
spec:
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: company == "sleepy"