apiVersion: v1
kind: Namespace
metadata:
  name: lab4-namespace 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-deployment  
  namespace: lab4-namespace
spec:
  selector:
    matchLabels:
      app: lab4
  replicas: 2 
  template:
    metadata:
      labels:
        app: lab4
    spec:
      containers:
      - name: lab4
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          value: "artshirshov"
        - name: REACT_APP_COMPANY_NAME
          value: "ITMO"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: lab4-service  
  namespace: lab4-namespace
  labels:
    run: lab4
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: lab4
