apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:        
        - name: lab2
          image: ifilyaninitmo/itdt-contained-frontend:master
          env:
          - name: REACT_APP_USERNAME
            value: artem
          - name: REACT_APP_COMPANY_NAME
            value: artshirshov
          ports:
            - containerPort: 31000