apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    name: hello
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  selector:
    app: hello
  type: NodePort